DROP TABLE COMMENT_LIKED;
DROP TABLE POSTS_HAVE;
DROP TABLE COMMENTS;
DROP TABLE SHARES;
DROP TABLE PHOTOS;
DROP TABLE POSTS_LIKED;
DROP TABLE POSTS;
DROP TABLE PAGE_LIKED;
DROP TABLE PAGES;
DROP TABLE FRIENDS;
DROP TABLE PERMISSIONS;
DROP TABLE ROLES;
DROP TABLE LOGINS;
DROP TABLE USERS;

CREATE TABLE USERS(
    USER_ID NUMBER(10) NOT NULL,
    USERNAME VARCHAR2(20),
    USER_MOBILE NUMBER(11),
    USER_EMAIL VARCHAR2(50),
    USER_ADDRESS VARCHAR2(50),
    PRIMARY KEY(USER_ID)
);

CREATE TABLE LOGINS(
    LOGIN_ID NUMBER(10) NOT NULL,
    LOGIN_USERNAME VARCHAR2(20),
    USER_PASSWORD VARCHAR2(20),
    PRIMARY KEY(LOGIN_ID),
    FOREIGN KEY(LOGIN_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ROLES (
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(20),
    ROLE_DESC VARCHAR2(50),
    PRIMARY KEY(ROLE_ID),
    FOREIGN KEY(ROLE_ID) REFERENCES LOGINS(LOGIN_ID)
);

CREATE TABLE PERMISSIONS (
    PER_ID NUMBER(10) NOT NULL,
    PER_NAME VARCHAR2(20),
    PER_MODULE VARCHAR2(30),
    PRIMARY KEY(PER_ID),
    FOREIGN KEY(PER_ID) REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE FRIENDS (
    FRIEND_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY (FRIEND_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE PAGES (
    PAGE_ID NUMBER(15) NOT NULL,
    PAGE_NAME VARCHAR2(30),
    PAGE_CONTENT VARCHAR2(50),
    PRIMARY KEY(PAGE_ID)
);

CREATE TABLE PAGE_LIKED (
    PAGE_ID NUMBER(15) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY(PAGE_ID),
    FOREIGN KEY(PAGE_ID) REFERENCES PAGES(PAGE_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE POSTS (
    POST_ID NUMBER(12) NOT NULL,
    POST_CONTENT VARCHAR2(50),
    POST_DATE DATE,
    USER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY(POST_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE POSTS_LIKED (
    POST_ID NUMBER(12) NOT NULL,
    USER_ID NUMBER(10),
    PRIMARY KEY(POST_ID),
    FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID)
);

CREATE TABLE PHOTOS (
    PHOTO_ID NUMBER(8) NOT NULL,
    IMAGE_CONTENT VARCHAR2(64),
    POST_ID NUMBER(12) NOT NULL,
    PRIMARY KEY(PHOTO_ID)
);

CREATE TABLE SHARES (
    POST_ID NUMBER(12) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY(POST_ID),
    FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID)
);

CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    POST_ID NUMBER(12) NOT NULL,
    COMMENT_DATE DATE,
    COMMENT_CONTENT VARCHAR2(50),
    PRIMARY KEY(COMMENT_ID),
    FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID)
);

CREATE TABLE POSTS_HAVE (
    POST_ID NUMBER(12) NOT NULL,
    PHOTO_ID NUMBER(8) NOT NULL,
    PRIMARY KEY(POST_ID, PHOTO_ID),
    FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID),
    FOREIGN KEY(PHOTO_ID) REFERENCES PHOTOS(PHOTO_ID)
);

CREATE TABLE COMMENT_LIKED (
    COMMENT_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY(COMMENT_ID),
    FOREIGN KEY(COMMENT_ID) REFERENCES COMMENTS(COMMENT_ID)
);

